# Generated by Django 3.1.7 on 2021-03-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified_chinese', models.CharField(max_length=16)),
                ('traditional_chinese', models.CharField(blank=True, max_length=16)),
                ('pinyin', models.CharField(max_length=64)),
                ('pin_num', models.CharField(blank=True, max_length=64)),
                ('pin_plain', models.CharField(blank=True, max_length=64)),
                ('english', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Vocabulary',
                'verbose_name_plural': 'Vocabulary',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vocabulary')),
            ],
        ),
    ]
