# Generated by Django 3.1.7 on 2021-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary_group',
            name='character',
        ),
        migrations.AddField(
            model_name='vocabulary_group',
            name='character',
            field=models.ManyToManyField(to='core.Vocabulary'),
        ),
    ]
